# Generated by Django 2.1.2 on 2018-11-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_linkedinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateproduct',
            name='unit',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
