# Generated by Django 2.1.2 on 2018-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_linkedproductrecord_privateproductrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedproductrecord',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='privateproductrecord',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
