# Generated by Django 2.1.2 on 2018-11-20 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_merge_20181108_0939'),
        ('inventory', '0006_auto_20181110_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinventory',
            name='id_unidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
        migrations.AddField(
            model_name='linkedproductrecord',
            name='id_unidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
    ]
