# Generated by Django 2.1.2 on 2018-11-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20181119_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='linkedinventory',
            name='id_unidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
        migrations.AlterField(
            model_name='linkedproductrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='linkedproductrecord',
            name='id_unidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
        migrations.AlterField(
            model_name='privateproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='privateproductrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
