# Generated by Django 2.1.2 on 2018-11-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0003_privateproduct'),
        ('provider', '0010_linkwithf_date_of_creation'),
        ('products', '0017_equivalencias_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(verbose_name='date published')),
                ('fecha_ideal', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(null=True)),
                ('preico_total', models.DecimalField(decimal_places=3, max_digits=8)),
                ('activo', models.BooleanField()),
                ('id_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise')),
                ('id_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('activo', models.BooleanField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductInState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=3, max_digits=8)),
                ('comentario', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('activo', models.BooleanField()),
                ('id_complete_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CompleteProduct')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orderproductinstate',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderProductState'),
        ),
        migrations.AddField(
            model_name='orderinstate',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderState'),
        ),
    ]
