# Generated by Django 2.1.2 on 2018-11-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_equivalencias_activo'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderInState',
            new_name='OrderInStatus',
        ),
        migrations.RenameModel(
            old_name='OrderProductInState',
            new_name='OrderProductInStatus',
        ),
        migrations.RenameModel(
            old_name='OrderProductState',
            new_name='OrderProductStatus',
        ),
        migrations.RenameModel(
            old_name='OrderState',
            new_name='OrderStatus',
        ),
        migrations.RenameField(
            model_name='orderinstatus',
            old_name='id_state',
            new_name='id_status',
        ),
        migrations.RenameField(
            model_name='orderproductinstatus',
            old_name='id_state',
            new_name='id_status',
        ),
        migrations.AddField(
            model_name='order',
            name='arrive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
