# Generated by Django 2.1.2 on 2018-11-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181106_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='preico_total',
            new_name='precio_total',
        ),
    ]
