# Generated by Django 2.1.2 on 2018-11-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181107_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='precio_total',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
