# Generated by Django 2.1.2 on 2018-11-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_merge_20181108_0939'),
        ('orders', '0005_auto_20181107_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductinstatus',
            name='id_unidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
        migrations.AddField(
            model_name='orderproductinstatus',
            name='precio_por_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
