# Generated by Django 2.1.2 on 2018-12-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181110_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductinstatus',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
