# Generated by Django 2.1.2 on 2018-12-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproductinstatus_cantidad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
