# Generated by Django 2.1.2 on 2018-10-09 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.TextField(max_length=200)),
                ('mision', models.TextField(max_length=4000)),
                ('vision', models.TextField(max_length=4000)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(verbose_name='date published')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
