# Generated by Django 2.1.2 on 2018-10-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='vision',
        ),
    ]
