# Generated by Django 2.1.2 on 2018-10-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocsuser',
            name='direccion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocsuser',
            name='num_ss',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocsuser',
            name='rfc',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
