# Generated by Django 2.1.2 on 2018-10-09 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20181008_1914'),
        ('franchise', '0002_auto_20181008_1941'),
        ('accounts', '0002_auto_20181008_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocsuser',
            name='id_franchise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocsuser',
            name='id_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
            preserve_default=False,
        ),
    ]
