# Generated by Django 2.1.2 on 2018-10-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181008_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocsuser',
            name='id_franchise',
        ),
    ]
