# Generated by Django 2.1.2 on 2018-10-09 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_auto_20181008_1941'),
        ('accounts', '0004_remove_ocsuser_id_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocsuser',
            name='id_franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise'),
            preserve_default=False,
        ),
    ]
