# Generated by Django 2.1.2 on 2018-10-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ocsuser_id_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocsuser',
            name='id_franchise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise'),
        ),
        migrations.AlterField(
            model_name='ocsuser',
            name='id_provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
