# Generated by Django 2.1.2 on 2018-10-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0008_ispoviderorfranchise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IsPoviderOrFranchise',
            new_name='IsProviderOrFranchise',
        ),
    ]
