# Generated by Django 2.1.2 on 2018-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181012_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocsuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
