# Generated by Django 2.1.2 on 2018-10-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('correo_empleado', models.CharField(max_length=200)),
                ('RFC_empleado', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_privilegio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RolPrivilegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Privilegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Privilegio')),
                ('id_Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_Rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Rol'),
        ),
    ]
