# Generated by Django 2.1.2 on 2018-10-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_proveedor',
            new_name='id_provider',
        ),
    ]
