# Generated by Django 2.1.2 on 2018-10-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20181008_1914'),
        ('products', '0002_auto_20181008_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='Product',
        ),
    ]
