# Generated by Django 2.1.2 on 2018-10-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181008_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
