# Generated by Django 2.1.2 on 2018-10-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_privateproduct'),
        ('products', '0004_product_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amou', models.IntegerField()),
                ('id_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
