# Generated by Django 2.1.2 on 2018-10-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_linkedinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinventory',
            old_name='amou',
            new_name='amount',
        ),
    ]
