# Generated by Django 2.1.2 on 2018-11-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181024_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='date published')),
                ('fecha_final', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviacion', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='completeproduct',
            name='id_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Price'),
        ),
        migrations.AddField(
            model_name='completeproduct',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='completeproduct',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
    ]
