# Generated by Django 2.1.2 on 2018-11-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181024_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinventory',
            name='id_franchise',
        ),
        migrations.RemoveField(
            model_name='linkedinventory',
            name='id_product',
        ),
        migrations.DeleteModel(
            name='LinkedInventory',
        ),
    ]
