# Generated by Django 2.1.2 on 2018-11-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_price_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='fecha_final',
            field=models.DateTimeField(null=True),
        ),
    ]
