# Generated by Django 2.1.2 on 2018-11-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181103_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeproduct',
            name='id_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Price'),
        ),
        migrations.AlterField(
            model_name='completeproduct',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='completeproduct',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnidadDeMedida'),
        ),
    ]
