# Generated by Django 2.1.2 on 2018-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181103_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
