# Generated by Django 2.1.2 on 2018-11-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181104_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeproduct',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
