# Generated by Django 2.1.2 on 2018-11-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_completeproduct_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_origen', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('cantidad_destino', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('id_unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_unidad_destino', to='products.UnidadDeMedida')),
                ('id_unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_unidad_origen', to='products.UnidadDeMedida')),
            ],
        ),
    ]
