# Generated by Django 2.1.2 on 2018-11-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_equivalencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalencias',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
