# Generated by Django 2.1.2 on 2018-11-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181102_1606'),
        ('products', '0017_equivalencias_activo'),
    ]

    operations = [
    ]
