# Generated by Django 2.1.2 on 2018-10-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='provedor',
            new_name='proveedor',
        ),
    ]
