# Generated by Django 2.1.2 on 2018-10-09 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181008_1914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0004_proveedor_id_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proveedor',
            new_name='Provider',
        ),
    ]
