# Generated by Django 2.1.2 on 2018-10-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_auto_20181008_1941'),
        ('provider', '0005_auto_20181008_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkWithF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.CharField(max_length=12)),
                ('active', models.BooleanField()),
                ('used', models.BooleanField()),
                ('id_franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise')),
                ('id_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
    ]
