# Generated by Django 2.1.2 on 2018-10-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_days_officehours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehours',
            name='finish_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='start_hour',
            field=models.TimeField(),
        ),
    ]
