# Generated by Django 2.1.2 on 2018-10-21 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_auto_20181008_1941'),
        ('provider', '0008_auto_20181016_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Days')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise')),
            ],
        ),
    ]
