# Generated by Django 2.1.2 on 2018-10-25 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_dailyclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkwithf',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
