# Generated by Django 2.1.2 on 2018-12-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_linkwithf_date_of_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyclients',
            old_name='franchise',
            new_name='id_franchise',
        ),
        migrations.AddField(
            model_name='dailyclients',
            name='id_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
