# Generated by Django 2.1.2 on 2018-12-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_auto_20181217_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyclients',
            name='status',
        ),
        migrations.AddField(
            model_name='dailyclients',
            name='activo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
