# Generated by Django 2.1.2 on 2018-12-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20181217_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkwithf',
            name='is_daily_client',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
